# This file was automatically generated by APIMATIC BETA v2.0 on 02/12/2016

module ApimaticCalculator 
  class Configuration

    # The base Uri for API calls
    @BASE_URI = "https://examples.apimatic.io/apps/calculator"


    # create the getters and setters
    class << self
      attr_accessor :BASE_URI

    end
  end
end
